### ISSUE TITLE
Separate SSL consideration from PHP code

### ISSUE THREAD

**Issue by namenu** [ridibooks/cms-sdk#2]
Method `conformAllowedProtocol` from MiniRouter forces to use http or https.
This is bad practice since it's a matter of transportation layer, not the application layer.

Make MiniRouter work for both http/https and let the web server decide whether to disable or enable http.

**Comment by imkitae** [comment]
https://github.com/ridibooks/cms-sdk/commit/1c20c7a01c08ac674cdef900b49d086d5dfcb178
